app/urls.py
from . import views
from django.urls import reverse_lazy
from django.urls import path, include, re_path
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from .forms import LoginForm, PasswordResetForm, SetPasswordForm

app_name = 'app'

urlpatterns = [
    path('', login_required(RedirectView.as_view(url='page', permanent=False)), name='home'),

    path('keywords', views.KeywordListPage.as_view(), name='keywords'),
    path('keywords/ip/<int:pk>/<int:count>', views.KeywordIpDetailPage.as_view(), name='keyword_ip_detail'),
    path('keywords/scrape/<int:pk>', views.KeywordScrapeView.as_view(), name='keywords_scrape'),
    re_path(r'keywords/export$', views.export_excel, name='keywords_export'),

    path('smsblast/contact', views.ContactView.as_view(), name='smsblast_contact'),
    path('smsblast/add_contact', views.AddContactMethodsView.as_view(), name='smsblast_add_contact'),
    path('smsblast/detail_contact/<str:pk>', views.DetailContactView.as_view(), name='smsblast_detail_contact'),
    path('smsblast/update_contact/<str:pk>', views.UpdateContactView.as_view(), name='smsblast_update_contact'),
    path('smsblast/delete_contact/<str:pk>', views.DeleteContactView.as_view(), name='smsblast_delete_contact'),

    path('smsblast/add_contact_group', views.AddContactGroupView.as_view(), name='smsblast_add_contact_group'),
    path('smsblast/add_random_generated_numbers', views.AddRandomGeneratedNumbersView.as_view(), name='smsblast_add_random_generated_numbers'),
    path('smsblast/generate_random_number_add', views.GenerateRandomContactViewAdd.as_view(), name='generate_random_contact_add'),
    path('smsblast/generate_csv_add', views.GenerateCSVContactViewAdd.as_view(), name='generate_csv_add'),
    path('smsblast/temp_random_contacts_add', views.TempRandomContactViewAdd.as_view(), name='temp_random_contacts_add'),
    path('smsblast/temp_csv_contacts_add', views.TempCSVContactViewAdd.as_view(), name='temp_csv_contacts_add'),

    path('smsblast/update_contact_group/<str:pk>', views.UpdateContactGroupView.as_view(), name='smsblast_update_contact_group'),
    path('smsblast/update_random_generated_numbers/<str:pk>', views.UpdateRandomGeneratedNumbersView.as_view(), name='smsblast_update_random_generated_numbers'),
    path('smsblast/generate_random_number_update', views.GenerateRandomContactViewUpdate.as_view(), name='generate_random_contact_update'),
    path('smsblast/generate_csv_update', views.GenerateCSVContactViewUpdate.as_view(), name='generate_csv_udpate'),
    path('smsblast/temp_random_contacts_update', views.TempRandomContactViewUpdate.as_view(), name='temp_random_contacts_update'),
    path('smsblast/temp_csv_contacts_update', views.TempCSVContactViewUpdate.as_view(), name='temp_csv_contacts_update'),
    path('smsblast/download_csv_template', views.download_csv_template, name='download_csv_template'),

    path('smsblast', views.SMSBlastView.as_view(), name='smsblast'),
    path('smsblast/add_smsblast', views.AddSMSBlastView.as_view(), name='smsblast_add_smsblast'),
    path('smsblast/add_smsblast_temp_contacts', views.SMSBlastTempContactsViewAdd.as_view(), name='smsblast_add_smsblast_temp_contacts'),
    path('smsblast/update_smsblast_temp_contacts', views.SMSBlastTempContactsViewUpdate.as_view(), name='smsblast_update_smsblast_temp_contacts'),
    path('smsblast/check_contact_add/<str:source>/<str:name>/<int:count>', views.CheckContactViewAdd.as_view(), name='smsblast_check_contact_add'),
    path('smsblast/detail_smsblast/<str:pk>', views.DetailSMSBlastView.as_view(), name='smsblast_detail_smsblast'),
    path('smsblast/detail_smsblast_status/<str:pk>', views.DetailSMSBlastStatusView.as_view(), name='smsblast_detail_smsblast_status'),
    path('smsblast/update_smsblast/<str:pk>', views.UpdateSMSBlastView.as_view(), name='smsblast_update_smsblast'),
    path('smsblast/delete_smsblast/<str:pk>', views.DeleteSMSBlastView.as_view(), name='smsblast_delete_smsblast'),

    path('app', views.AppView.as_view(), name='app'),
    path('app/add_app', views.AddAppView.as_view(), name='add_app'),
    path('app/update_app/<str:pk>', views.UpdateAppView.as_view(), name='update_app'),
    path('app/archive_app/<str:pk>', views.ArchiveAppView.as_view(), name='archive_app'),
    path('app/delete_app/<str:pk>', views.DeleteAppView.as_view(), name='delete_app'),

    path('page', views.PageView.as_view(), name='page'),
    path('page/add_page', views.AddPageView.as_view(), name='add_page'),
    path('page/update_page/<str:pk>', views.UpdatePageView.as_view(), name='update_page'),
    path('page/archive_page/<str:pk>', views.ArchivePageView.as_view(), name='archive_page'),
    path('page/delete_page/<str:pk>', views.DeletePageView.as_view(), name='delete_page'),
    path('location/active_location/<str:pk>', views.ActiveLocationView.as_view(), name='active_location'),

    path('banner', views.BannerView.as_view(), name='banner'),
    path('banner/add_banner', views.AddBannerView.as_view(), name='add_banner'),
    path('banner/update_banner/<str:pk>', views.UpdateBannerView.as_view(), name='update_banner'),
    path('banner/archive_banner/<str:pk>', views.ArchiveBannerView.as_view(), name='archive_banner'),
    path('banner/delete_banner/<str:pk>', views.DeleteBannerView.as_view(), name='delete_banner'),

    path('installation', views.InstallationView.as_view(), name='install'),
    path('installation/add_installation', views.AddInstallationView.as_view(), name='add_install'),
    path('installation/detail_installation/<str:pk>', views.DetailInstallationView.as_view(), name='detail_install'),
    path('installation/update_installation/<str:pk>', views.UpdateInstallationView.as_view(), name='update_install'),
    path('installation/delete_installation/<str:pk>', views.DeleteInstallationView.as_view(), name='delete_install'),

    path('user', views.UserView.as_view(), name='user'),
    path('user/add_user', views.AddUserView.as_view(), name='add_user'),
    path('user/update_user', views.UpdateUserView.as_view(), name='update_user'),
    path('user/update_user/username/<int:pk>', views.UpdateUsernameView.as_view(), name='update_username'),
    path('user/update_user/email/<int:pk>', views.UpdateEmailView.as_view(), name='update_email'),
    path('user/update_user/password/<int:pk>', views.UpdatePasswordView.as_view(), name='update_password'),
    path('user/delete_user/<int:pk>', views.DeleteUserView.as_view(), name='delete_user'),

    path('ajax/check-priority-available-add', views.check_priority_available_add, name='ajax_check_priority_available_add'),
    path('ajax/check-priority-available-update', views.check_priority_available_update, name='ajax_check_priority_available_update'),
    path('ajax/check-campaign-code-available-add', views.check_campaign_code_available_add, name='ajax_check_campaign_code_available_add'),
    path('ajax/check-campaign-code-available-update', views.check_campaign_code_available_update, name='ajax_check_campaign_code_available_update'),
    path('ajax/load-pages', views.load_pages, name='ajax_load_pages'),
    path('ajax/load-locations', views.load_locations, name='ajax_load_locations'),
    path('ajax/load-banner', views.load_banner, name='ajax_load_banner'),
    path('ajax/load-location-size', views.load_location_size, name='ajax_load_location_size'),
    path('ajax/load-regions', views.load_regions, name='ajax_load_regions'),
    path('ajax/load-cities', views.load_cities, name='ajax_load_cities'),
    path('ajax/load-contacts', views.load_contacts, name='ajax_load_contacts'),
    path('ajax/check-similar-page-add', views.check_similar_page_add, name='ajax_check_similar_page_add'),
    path('ajax/check-similar-page-update', views.check_similar_page_update, name='ajax_check_similar_page_update'),
    path('ajax/check-similar-location-add', views.check_similar_location_add, name='ajax_check_similar_location_add'),
    path('ajax/check-similar-location-update', views.check_similar_location_update, name='ajax_check_similar_location_update'),
    path('ajax/check-location-code-add', views.check_location_code_available_add, name='ajax_check_location_code_add'),
    path('ajax/check-location-code-update', views.check_location_code_available_update, name='ajax_check_location_code_update'),
    path('ajax/check-app-name-add', views.check_similar_app_name_add, name='ajax_check_app_name_add'),
    path('ajax/check-app-name-update', views.check_similar_app_name_update, name='ajax_check_app_name_update'),
    path('ajax/check-app-code-add', views.check_similar_app_code_add, name='ajax_check_app_code_add'),
    path('ajax/check-app-code-update', views.check_similar_app_code_update, name='ajax_check_app_code_update'),
    path('ajax/check-similar-date-add', views.check_similar_date_add, name='ajax_check_similar_date_add'),
    path('ajax/check-similar-date-update', views.check_similar_date_update, name='ajax_check_similar_date_update'),
    path('ajax/check-contact-name-add', views.check_contact_name_add, name='ajax_check_contact_name_add'),
    path('ajax/check-contact-name-update', views.check_contact_name_update, name='ajax_check_contact_name_update'),

    re_path(r'login$', auth_views.LoginView.as_view(authentication_form=LoginForm, redirect_authenticated_user=True), name='login'),
    path('password_reset', auth_views.PasswordResetView.as_view(form_class=PasswordResetForm, success_url=reverse_lazy('app:password_reset_done'), html_email_template_name='registration/password_reset_email.html', from_email='noreply@banner-slider-qa.holahalo.dev'), name='password_reset'),
    path('password_reset_done', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

slidercms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from api.router import router

urlpatterns = [
    path('', include('app.urls', namespace='app')),
    path('admin/', admin.site.urls),
    path('django-rq/', include('django_rq.urls')),
    path('api/v1/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/add_contact_form.html
{% extends 'app/base.html' %}

{% load static %}

{% block title %}SMS Blast - Tambah Kontak{% endblock title %}

{% block style %}<link rel="stylesheet" href="{% static 'css/add_contact.css' %}">{% endblock style %}

{% block content %}
<form id="contactGroupForm" method="POST" action="{% url 'app:smsblast_add_contact_group' %}" data-check-name-url="{% url 'app:ajax_check_contact_name_add' %}">
    {% csrf_token %}

    <div id="card-field" class="container-fluid mt-3">
        <h3 class="text-center mb-2">Form Tambah Kontak</h3>
    </div>

    <hr>

    <div class="container-fluid mt-5 mb-5">

        <div class="form-group row">
            <label class="col-sm-2 col-form-label"
                for="{{ form_contact.name.id_for_label }}">{{ form_contact.name.label }}</label>
            <div class="col-sm-10">
                {{ form_contact.name }}
                <small id="contactNameErrorEmpty" style="color: red; display: none;">Nama tidak boleh kosong.</small>
                <small id="contactNameErrorNotUnique" style="color: red; display: none;">Nama sudah dipakai. Silahkan coba nama lain.</small>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label"
                for="{{ form_contactsource.source.id_for_label }}">{{ form_contactsource.source.label }}</label>
            <div class="col-sm-10">
                {{ form_contactsource.source }}

                {% if form_contactsource.errors %}
                {% for error in form_contactsource.source.errors %}
                <small style="color: red;">{{error}}</small>
                {% endfor %}
                {% endif %}

            </div>
        </div>

        <input id="csvBool" type="hidden" name="csvBool">

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Generate Nomor Tujuan</label>
        </div>

        <button id="contactGroupFormBtn" style="display: none;" type="submit">Submit</button>

    </div>
</form>

<form id="randomNumberForm" method="POST" action="{% url 'app:smsblast_add_random_generated_numbers' %}">
    {% csrf_token %}
    {{ formset_generaterandomnumber.management_form }}
    <fieldset {% if not form_generate_fail %}style="display: none;"{% endif %} id="random-generate" class="numbergenerate-border">
        <div class="control-group mb-3 mt-3">
            <div class="col input-wrapper">
                {% for form_generate in formset_generaterandomnumber %}
                <div id="generate-{{forloop.counter0}}-div" class="row generate-div" class="row">
                    <div class="col-sm-2 no-padding">
                        <label for="">{{form_generate.first_code.label}}</label>
                        <div class="input-group">
                            {{form_generate.first_code}}
                        </div>
                        <div class="input-group">
                            <small id="first_code-{{forloop.counter0}}-inaccurate" class="first_code-inaccurate"
                                style="color: red; display: none;">Kode Awal harus berawalan 08 dan maksimal 4 karakter.</small>

                            {% if form_generate.errors %}
                            {% for error in form_generate.first_code.errors %}
                            <small class="first_code-backend-error" style="color: red;">{{error}}</small>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-sm-3 no-padding">
                        <label for="">{{form_generate.digits.label}}</label>
                        <div class="input-group">
                            {{form_generate.digits}}
                        </div>
                        <div class="input-group">
                            <small id="digits-{{forloop.counter0}}-inaccurate" class="digits-inaccurate"
                                style="color: red; display: none;">Jumlah digit nomor harus diisi dengan angka antara 9 - 14.</small>

                            {% if form_generate.errors %}
                            {% for error in form_generate.digits.errors %}
                            <small class="digits-backend-error" style="color: red;">{{error}}</small>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-sm-3 no-padding">
                        <label for="">{{form_generate.generate_numbers.label}}</label>
                        <div class="input-group">
                            {{form_generate.generate_numbers}}
                        </div>
                        <div class="input-group">
                            <small id="generate_numbers-{{forloop.counter0}}-empty" class="generate_numbers-inaccurate"
                                style="color: red; display: none;">Jumlah nomor yang akan di Generate tidak boleh kosong.</small>

                            <small id="generate_numbers-{{forloop.counter0}}-exceeded" class="generate_numbers-inaccurate"
                                style="color: red; display: none;">Maksimal Nomor yang bisa di-generate adalah
                                100.000.</small>

                            {% if form_generate.errors %}
                            {% for error in form_generate.generate_numbers.errors %}
                            <small class="generate_numbers-backend-error" style="color: red;">{{error}}</small>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div id="contactBtnDiv" class="col-sm-2">
                        <label style="color: white;">tambah&hapus</label>
                        <div class="input-group">
                            <button id="add-{{forloop.counter0}}-contact" type="button"
                                class="btn btn-primary addContactBtn"
                                onclick="addContact(this);">Tambah</button>
                            <button style="display: none;" id="delete-{{forloop.counter0}}-contact" type="button"
                                class="btn btn-danger deleteContactBtn ml-2"
                                onclick="deleteContact(this);">Hapus</button>
                        </div>
                    </div>
                    
                </div>
                {% endfor %}

                <div class="row">
                    <div class="col-sm-3">
                        <label style="color: white;"></label>
                        <div class="input-group">
                            <button id="generateNumber" type="button" class="btn btn-success">Generate</button>
                            <a id="tempRandomContacts" href="{% url 'app:temp_random_contacts_add' %}" target="_blank">
                                <button id="viewRandomNumbers" type="button" class="btn btn-warning ml-2" disabled>Lihat
                                    Nomor</button>
                            </a>

                            <div id="randomNumberSpinner" style="display: none;" class="spinner-border ml-3 mt-1" role="status">
                                <span class="sr-only">Loading...</span>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>

        <input id="contactName" type="hidden" name="contactName" {% if contact_name %}value="{{contact_name}}"{% endif %}>

        <button id="generateRandomFormBtn" style="display: none;" type="submit">Submit</button>
    </fieldset>
</form>

<form id="csvForm" action="{% url 'app:generate_csv_add' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset style="display: none;" id="csv-generate" class="numbergenerate-border">
        <div class="control-group mb-3 mt-3">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label"
                    for="{{form_uploadcsv.upload_csv.id_for_label}}">{{form_uploadcsv.upload_csv.label}}</label>
                <div class="col-sm-10">
                    {{form_uploadcsv.upload_csv}}
                    <small id="csv-inaccurate" class="csv-errors" style="color: red; display: none;">File tidak sesuai atau tidak boleh kosong.</small>
                    <small id="csv-invalid-format" class="csv-errors" style="color: red; display: none;">Format CSV tidak sesuai dengan template.</small>
                    <small id="csv-invalid-prefix" class="csv-errors" style="color: red; display: none;">Nomor harus berawalan 08.</small>
                    <small id="csv-invalid-length" class="csv-errors" style="color: red; display: none;">Jumlah digit nomor harus di antara 9 - 14.</small>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <label style="color: white;"></label>
                    <div class="input-group">
                        <a href="{% url 'app:download_csv_template' %}">
                            <button id="downloadCSVTemplate" type="button" class="btn btn-success">Download
                                Template</button>
                        </a>
                        <a id="tempCSVContacts" href="{% url 'app:temp_csv_contacts_add' %}" target="_blank">
                            <button id="viewCSVNumbers" type="button" class="btn btn-warning ml-2" disabled>Lihat
                                Nomor</button>
                        </a>
                        <div id="csvNumberSpinner" style="display: none;" class="spinner-border ml-3 mt-1" role="status">
                            <span class="sr-only">Loading...</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
</form>

<div class="container-fluid mt-5 mb-5">

    <div {% if not form_generate_fail %}style="display: none;"{% endif %} id="saveBtnDiv" class="form-group row float-right">
        <a href="{% url 'app:smsblast_contact' %}">
            <button type="button" class="btn btn-secondary">Batal</button>
        </a>
        <button id="submitForms" type="button" class="btn btn-primary ml-2" onclick="submitForms();" disabled>Simpan</button>
    </div>

</div>


{% endblock content %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/autonumeric/4.1.0/autoNumeric.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        new AutoNumeric('.generate_numbers', {
            digitGroupSeparator : '.',
            decimalPlaces : '0',
            decimalCharacter : ',',
        });

        {% if form_generate_fail %}
        window.history.pushState('', '', '/smsblast/add_contact');
        $('#id_source').val('random').attr('selected', true)

        var showdeleteId = $('#id_form-TOTAL_FORMS').val() - 1
        if (showdeleteId != 0) {
            $('#delete-' + ($('#id_form-TOTAL_FORMS').val() - 1) + '-contact').show();
        }
        {% endif %}

        $('#sliderManagement').removeClass('menu-open');
        $('a#contactManagement').addClass('active');

        $('#id_source').select2({
            theme: 'bootstrap4',
            placeholder: 'Pilih cara mendapatkan sumber kontak',
        });
    });
</script>
<script src="{% static 'js/add_contact.js' %}"></script>
{% endblock script %}

templates/app/detail_smsblast.html
{% extends 'app/base.html' %}

{% load static %}

{% block title %}SMS Blast - Detail Kontak{% endblock title %}

{% block style %}<link rel="stylesheet" href="{% static 'css/detail_smsblast.css' %}">{% endblock style %}

{% block content %}
    <h3 class="text-center mb-2">Detail Pengiriman SMS
        <span class="btn-group float-right">
            <a href="{% url 'app:smsblast' %}" style="color: white; text-decoration: none;">
                <button type="button" class="btn btn-secondary mr-2">
                    Kembali
                </button>
            </a>
        </span>
    </h3>

<hr>

<div class="form-group row mt-2">
    <label class="col-sm-2 col-form-label" for="">
        <strong>Nama Grup Kontak</strong>
    </label>
    <label class="col-sm-1 col-form-label no-padding" style="max-width: 3% !important">:</label>
    <div class="col-sm-9 no-padding">
        <input type="text" class="form-control no-border" value="{{contacts}}" disabled>
    </div>
</div>

<div class="form-group row mt-2">
    <label class="col-sm-2 col-form-label" for="">
        <strong>Lihat Status Pesan</strong>
    </label>
    <label class="col-sm-1 col-form-label no-padding" style="max-width: 3% !important">:</label>
    <div class="col-sm-9 no-padding">
        <a href="{% url 'app:smsblast_detail_smsblast_status' pk=pk %}">
            <button class="btn btn-warning">Lihat Nomor</button>
        </a>
    </div>
</div>

<div class="form-group row mt-2">
    <label class="col-sm-2 col-form-label" for="">
        <strong>Judul Pesan</strong>
    </label>
    <label class="col-sm-1 col-form-label no-padding" style="max-width: 3% !important">:</label>
    <div class="col-sm-9 no-padding">
        <input type="text" class="form-control no-border" value="{{smsblast.message_title}}" disabled>
    </div>
</div>

<div class="form-group row mt-2">
    <label class="col-sm-2 col-form-label" for="">
        <strong>Isi Pesan</strong>
    </label>
    <label class="col-sm-1 col-form-label no-padding" style="max-width: 3% !important">:</label>
    <div class="col-sm-9 no-padding">
        <textarea a rows="3" cols="50" class="form-control no-border" disabled>{{smsblast.message_text}}</textarea>
    </div>
</div>

<div class="form-group row mt-2">
    <label class="col-sm-2 col-form-label" for="">
        <strong>Tanggal Pengiriman</strong>
    </label>
    <label class="col-sm-1 col-form-label no-padding" style="max-width: 3% !important">:</label>
    <div class="col-sm-9 no-padding">
        <input type="text" class="form-control no-border" value="{{smsblast.send_date|date:'d/m/Y'}}" disabled>
    </div>
</div>

<div class="form-group row mt-2">
    <label class="col-sm-2 col-form-label" for="">
        <strong>Jam Kirim</strong>
    </label>
    <label class="col-sm-1 col-form-label no-padding" style="max-width: 3% !important">:</label>
    <div class="col-sm-9 no-padding">
        <input type="text" class="form-control no-border" value="{{smsblast.send_time|time:'H:i:s'}}" disabled>
    </div>
</div>

{% endblock content %}

templates/app/regions_dropdown_list_options.html
<option value="">Pilih Wilayah</option>
{% for region in regions %}
<option value="{{ region }}">{{ region }}</option>
{% endfor %}

templates/app/update_page_form.html
{% extends 'app/base.html' %}

{% load static %}

{% block title %}Update Halaman{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/update_page.css' %}">
{% endblock style %}
    
{% block content %}
<form id="pageForm" method="POST" action="{% url 'app:update_page' pk=page.id %}"
    data-check-similar-page-url="{% url 'app:ajax_check_similar_page_update' %}"
    data-check-similar-location-url="{% url 'app:ajax_check_similar_location_update' %}"
    data-check-location-code-url="{% url 'app:ajax_check_location_code_update' %}">
    {% csrf_token %}

    {{ formset_page.management_form }}
    {{ formset_location.management_form }}

    <div id="card-field" class="container-fluid mt-3">

        <h3 class="text-center mb-2">Form Update Halaman
            <span class="btn-group float-right">
                <button id="submitUpdatePage" type="submit" class="btn btn-primary">Simpan</button>
            </span>
            <span class="btn-group float-right">
                <a href="{% url 'app:page' %}" style="color: white; text-decoration: none;">
                    <button type="button" class="btn btn-secondary mr-2">
                        Batal
                    </button>
                </a>
            </span>
        </h3>

        <hr>

        <div class="container-fluid mt-5 mb-5">
            <input type="hidden" id="actives-length" {% if True in actives %}value="True"{% else %}value="False"{% endif %}>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="{{ form_application.names.id_for_label }}">{{ form_application.names.label }}</label>
                <div class="col-sm-4">
                    {{ form_application.names }}
                </div>
            </div>

            {% for page in formset_page %}
            <div class="form-group row page-div">
                <label class="col-sm-2 col-form-label" for="{{ page.name.id_for_label }}">{{ page.name.label }}</label>
                <div class="col-sm-4">
                    {{ page.id }}
                    {{ page.name }}
                    <small id="id_warning-text-page" style="color: red; display: none;">Nama Halaman telah
                        dipakai. Silahkan masukkan nama lain.</small>
                </div>
            </div>
            {% endfor %}

            <div class="form-group">
                <h4>Daftar Lokasi Pemasangan:
                    <span class="btn-group float-right">
                        <button id="id_location-add" type="button" class="btn btn-primary float-right" onclick="cloneLocation();">Tambah Lokasi</button>
                    </span>
                </h4>
            </div>
            {% for location in formset_location %}
            {% with start=forloop.counter0|stringformat:"s" end=forloop.counter|stringformat:"s" %}
            {% with idSlice=""|add:start|add:":"|add:end %}
            {% with active=actives|slice:idSlice %}
                
            <fieldset id="id_location-{{ forloop.counter0 }}-fieldset" class="location-border fieldset">
                {{ location.DELETE }}
                {{ location.id }}
                
                <legend class="location-border">Lokasi ke-{{ forloop.counter }}</legend>

                <input type="hidden" id="id_location-{{ index }}-is_active" class="location-active" value="{{active.0}}">

                <div class="container">

                    <div class="location-div ml-5">

                        <div class="form-group row mb-0 location-slider">
                            <div class="col-sm-12">
                                <strong>
                                    <label class="radio-inline mr-2" for="{{ location.is_slider.id_for_label }}" style="color: #007bff;">{{ location.is_slider.label }}</label>
                                    {% for option in location.is_slider %}
                                    <label for="radio-inline" style="color: #007bff;">
                                        {{ option }}
                                    </label>
                                    {% endfor %}
                                </strong>
                            </div>    
                        </div>

                        <div class="form-group row location-code">
                            <label class="col-sm-3 col-form-label" for="{{ location.loc_code.id_for_label }}">{{ location.loc_code.label }}</label>
                            <div class="col-sm-9">
                                {{ location.loc_code }}
                                <small id="id_warning-text-location-code-{{ forloop.counter0 }}" class="location-code-warning-text" style="color: red; display: none;">
                                    Kode Lokasi telah dipakai. Silahkan masukkan kode lain.</small>
                            </div>
                        </div>

                        <div class="form-group row location-name">
                            <label class="col-sm-3 col-form-label" for="{{ location.name.id_for_label }}">{{ location.name.label }}</label>
                            <div class="col-sm-9">
                                {{ location.name }}
                                <small id="id_warning-text-location-{{ forloop.counter0 }}" class="location-warning-text" style="color: red; display: none;">
                                    Nama Lokasi telah dipakai. Silahkan masukkan nama lain.</small>
                            </div>
                        </div>

                        <div class="form-group row location-size">
                            <label class="col-sm-3 col-form-label mr-3" for="{{ location.width.id_for_label}}">{{ location.width.label }}</label>
                            {{ location.width }}

                            <label class="mr-2 ml-2" for="{{ location.height.id_for_label}}">{{ location.height.label }}</label>
                            {{ location.height }}            
                        </div>     

                    </div>

                    <button id="id_location-delete-{{ forloop.counter0 }}" type="button" class="btn btn-sm btn-danger float-right delete-btn"
                        onclick="removeLocation(this);">Hapus Lokasi</button>
                    
                </div>
                
            </fieldset>
            {% endwith %}
            {% endwith %}
            {% endwith %}
            {% endfor %}

        </div>

    </div>
</form>
{% endblock content %}

{% block script %}<script src="{% static 'js/update_page.js' %}"></script>{% endblock script %}
    